apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: dt-orders
      app.kubernetes.io/name: order-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: order-service
        app.kubernetes.io/version: "1"
        app.kubernetes.io/component: service
        app.kubernetes.io/part-of: dt-orders
        app.kubernetes.io/managed-by: helm
        app.kubernetes.io/created-by: dynatrace-demos
      annotations:
        owner: Team Services
        chat-channel: dev-team-services 
    spec:
      containers:
      - name: order
        image: dtdemos/dt-orders-order-service:1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: order-service
        env:
        - name: DT_CUSTOM_PROP
          value: "project=dt-orders service=order-service"
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app.kubernetes.io/part-of: dt-orders
    app.kubernetes.io/name: order-service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: order
  selector:
    app.kubernetes.io/part-of: dt-orders
    app.kubernetes.io/name: order-service
  type: ClusterIP