version: '3'
services:
  front-end:
    hostname: frontend
    image: dtdemos/dt-orders-frontend:1
    ports:
      - 80:8080
    environment:
      - BACKEND_URL=http://172.17.0.1:8080
      - MONOLITH=true
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=frontend owner=app-team-2 backend=monolith
      - DT_CLUSTER_ID=monolith-frontend
      - DT_APPLICATION_ENVIRONMENT=production
      - DT_APPLICATION_NAME=dt-orders-frontend
      - DT_APPLICATION_RELEASE_VERSION=1
      - DT_RELEASE_BUILD_VERSION=1
  backend-service:
    hostname: backend
    image: dtdemos/dt-orders-backend-monolith:1
    ports:
      - 8080:8080
    environment:
      - CUSTOMER_SERVICE_DOMAIN=172.17.0.1
      - CUSTOMER_SERVICE_PORT=8080
      - CATALOG_SERVICE_DOMAIN=172.17.0.1
      - CATALOG_SERVICE_PORT=8080
      - DT_CUSTOM_PROP=project=dt-orders stage=production service=backend owner=app-team-2
      - DT_CLUSTER_ID=monolith-backend
      - DT_APPLICATION_ENVIRONMENT=production
      - DT_APPLICATION_NAME=dt-orders-backend
      - DT_APPLICATION_RELEASE_VERSION=1
      - DT_RELEASE_BUILD_VERSION=1
  order-load:
    hostname: load
    image: dtdemos/dt-orders-load:1
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=80
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
      - MONOLITH=true
    restart: always